root: '管理员QQ号'
bot_uin: '机器人QQ号'
debug: false
check_ncatbot_update: true
napcat:
  ws_uri: ws://localhost:3001
  ws_token: YQnj193278@!jwdjo
  ws_listen_ip: localhost
  webui_uri: http://localhost:6099
  webui_token: '>%i2M#RqEVB{}8P$'
  enable_webui: true
  enable_update_check: false
  remote_mode: false
plugin:
  plugins_dir: plugins
  plugin_blacklist: []
  load_plugin: false
